// //OPERADORES ARITMETICOS

// let a = 15
// let b= 4

// suma = a+b

// console.log(`La suma de a + b es: ${suma}`);
// console.log("Resta: ", a-b);
// console.log("Multiplicación", a*b);
// console.log("Division", a/b);
// console.log("Modulo", a%b);

// //OERADORES DE COMPARACIÓN

// let edad1= 20;
// let edad2= 25;

// console.log("Edad 1 > Edad 2",edad1>edad2);
// console.log("Edad 1 < Edad 2",edad1<edad2);
// console.log("Edad 1 == Edad 2",edad1==edad2);
// console.log("Edad 1 != Edad 2",edad1!=edad2);
// console.log("Edad 1 >= Edad 2",edad1>=edad2);
// console.log("Edad 1 <= Edad 2",edad1<=edad2);

// //OPERADORES DE ASIGNACIÓN

// let puntos = 0; 

// puntos =puntos+10;
// puntos+=10 ;

// puntos -=5;
// puntos *=2;

// //OPERADORES LOGICOS

// let tieneTarea = false;
// let estudio= true;

// let puedeSalir = !tieneTarea && estudio;
// console.log(`¿Puede salir a jugar? ${puedeSalir}`);

// //OPERADOR TERNARIO

// let numero=9;
// let resultado = (numero % 2 ===0) ? "Par" : "Impar";
// console.log(`El numero es: ${resultado}`)



//EJERCICIOS 1

let c= 16;
let d = 6;

console.log(`El area de del triangulo es:`, (c*d)/2);

//EJERCICIOS 2

let N1= 11;
let N2= 24;

let COMPARACIÓN = (N1 > N2) ? "mayor" : (N1 < N2) ? "menor" : "igual";
console.log (`el numero es: ${COMPARACIÓN} que el segundo`);

//EJERCICIO 3

let NUM= 17;

let estaEnRango = ( NUM >= 10 && NUM <=20);
console.log(`El numero ${NUM} esta en el rando de 10 y 20 ${estaEnRango}`);



